###
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "userType" : "0",
  "login" : "eldik",
  "password" : "12345",
  "firstName" : "Eldiar",
  "lastName" : "Mambetaliev",
  "dateOfBirth" : "2006-04-19"
}

###
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "login" : "eldik",
  "password": "12345"
}

###
GET http://localhost:8080/api/info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NTUzNDMzNzMsImV4cCI6MTc1NTM0Mzk3Mywic3ViIjoiZWxkaWsifQ.yxxv3824ZJMcnd06ul1R1ITCIzbHtMK13F1zoi4S3YA

###
GET http://localhost:8080/api/infoAll
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NTUzNDMzNzMsImV4cCI6MTc1NTM0Mzk3Mywic3ViIjoiZWxkaWsifQ.yxxv3824ZJMcnd06ul1R1ITCIzbHtMK13F1zoi4S3YA
